# Generated by Django 4.2.1 on 2023-06-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='scientific_name',
        ),
    ]
