# Generated by Django 4.2.1 on 2023-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
